In [26]:
import numpy as np

In [27]:
arr1 = np.arange(12).reshape(3,4)
arr1.dtype

dtype('int32')

In [28]:
arr1 = arr1.astype(np.int64)

In [29]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [30]:
for i in arr1:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
for x in np.nditer(arr1, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [32]:
for x in np.nditer(arr1, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [33]:
for x in np.nditer(arr1, op_flags=['readwrite']):
    x[...] = x*x

In [35]:
arr1 # previously we were getting wrong values because of the overflow (due to dtype = int32)
# what is overflow
# The strange output you're seeing, with values like 2038349057 and negative numbers, suggests that there may be an issue related to integer overflow or data type mismatch.

# In NumPy, the default data type for integers is often int32 or int64, depending on the system. Squaring large numbers can exceed the maximum value that can be stored in these data types, leading to overflow and thus resulting in unexpected values.

# Potential Issues:
# Overflow: When an integer is squared and exceeds the maximum allowed value for its type, the result wraps around, leading to incorrect and often very large or negative numbers.
# Data Type: The data type of arr1 might be a lower-bit integer (int32), which has a limited range of values it can represent.

# so we fixed this thing by changing the type in line 3 
# arr1 = arr1.astype(np.int64)  by using this

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int64)

In [37]:
arr2 = np.arange(3,15,4).reshape(3,1)
arr2

array([[ 3],
       [ 7],
       [11]])

In [40]:
# at this moment we need to understand the general brodcasting rules: where one of the dimension of two array should be same
# so in these 2 arrays number of rows are same
for x,y in np.nditer([arr1, arr2]): 
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
