In [2]:
w1,w2,w3 = 0.3,0.2,0.5

In [3]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [4]:
weight = [w1,w2,w3]

In [5]:
def crop_yield(region, weight):
    result = 0
    for r,w in zip(region, weight):
        result += r * w
    return result

In [6]:
data = crop_yield(kanto,weight)
data

56.8

# NUMPY LIB

In [7]:
import numpy as np

In [8]:
# There are a couple of benifits of using Numpy arrays instead of python nlists for operating on numerical data:
# Ease of use: You can write small, concise and intutive mathematical expressions like (kanto * weight) .sum() rather than using loops
# & custom functions like crop_yield

# Performance:Numpy operations and functions are implemented internally in C++, which makes them much faster than using
# python statements & loops which are interpreted at runtime.

In [9]:
kanto = np.array([73, 67, 43])

In [10]:
np.dot(kanto,weight)

56.8

In [11]:
# Some other ways as well

In [12]:
(kanto*weight).sum()

56.8

In [13]:
# Python list
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1,dtype=np.int64)
arr2_np = np.array(arr2,dtype=np.int64)

In [14]:
%%time 
result = 0
for x1,x2 in zip(arr1, arr2):
    result += x1 * x2
result

CPU times: total: 156 ms
Wall time: 180 ms


833332333333500000

In [15]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 2.65 ms


833332333333500000

In [16]:
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 70]])

In [17]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [18]:
weights = np.array([0.3,0.2,0.5])

In [19]:
np.matmul(climate_data, weights) # matmul stands for matrix multiplication

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [20]:
climate_data @ weights # @ character represents the matrix multiplication

array([56.8, 76.9, 81.9, 57.7, 74.9])

# New_Excercise

In [21]:
import pandas as pd

climate_data = pd.read_csv("C:/Users/Monty/Desktop/Numpy/climate_data.txt", sep=",")
climate_data = np.genfromtxt('climate_data.txt',delimiter=',',skip_header=1)

In [22]:
climate_data

array([[ 26.24, 112.09,  78.4 ],
       [ 43.52,  99.87,  34.76],
       [ 36.96,  52.85,  47.73],
       ...,
       [ 43.4 ,  91.11,  21.56],
       [ 26.92, 133.  ,  52.08],
       [ 21.51,  51.68,  40.59]])

In [23]:
climate_data.shape

(10000, 3)

In [24]:
weights = np.array([0.3,0.2,0.5])

In [25]:
yields = climate_data @ weights

In [26]:
yields

array([69.49 , 50.41 , 45.523, ..., 42.022, 60.716, 37.084])

We can now add thew yields back to climate_data as fourth column using the np.concatenate function

In [27]:
climate_results = np.concatenate((climate_data,yields.reshape(10000, 1)),axis=1)

In [28]:
climate_results

array([[ 26.24 , 112.09 ,  78.4  ,  69.49 ],
       [ 43.52 ,  99.87 ,  34.76 ,  50.41 ],
       [ 36.96 ,  52.85 ,  47.73 ,  45.523],
       ...,
       [ 43.4  ,  91.11 ,  21.56 ,  42.022],
       [ 26.92 , 133.   ,  52.08 ,  60.716],
       [ 21.51 ,  51.68 ,  40.59 ,  37.084]])

# Here we are saving the new data as a txt file using np.savetxt command

In [29]:
np.savetxt('climate_results.txt',climate_results, fmt='%.2f',header='temperature,rainfall,humidity,yield_apples',
          comments='')

In [30]:
climate_results

array([[ 26.24 , 112.09 ,  78.4  ,  69.49 ],
       [ 43.52 ,  99.87 ,  34.76 ,  50.41 ],
       [ 36.96 ,  52.85 ,  47.73 ,  45.523],
       ...,
       [ 43.4  ,  91.11 ,  21.56 ,  42.022],
       [ 26.92 , 133.   ,  52.08 ,  60.716],
       [ 21.51 ,  51.68 ,  40.59 ,  37.084]])

In [31]:
climate_results[0,1:3]

array([112.09,  78.4 ])

In [32]:
climate_results[9999:, 1:]

array([[51.68 , 40.59 , 37.084]])

In [33]:
climate_results[:, 2]

array([78.4 , 34.76, 47.73, ..., 21.56, 52.08, 40.59])

In [34]:
climate_results[2::2, ::2]

array([[36.96, 47.73],
       [19.68, 58.57],
       [16.74, 96.9 ],
       ...,
       [18.74, 41.55],
       [41.93, 79.83],
       [26.92, 52.08]])

In [35]:
climate_results

array([[ 26.24 , 112.09 ,  78.4  ,  69.49 ],
       [ 43.52 ,  99.87 ,  34.76 ,  50.41 ],
       [ 36.96 ,  52.85 ,  47.73 ,  45.523],
       ...,
       [ 43.4  ,  91.11 ,  21.56 ,  42.022],
       [ 26.92 , 133.   ,  52.08 ,  60.716],
       [ 21.51 ,  51.68 ,  40.59 ,  37.084]])

In [36]:
def parse_header(first_line):
    return first_line.strip().split(',')

In [39]:
def parse_values(data_line):
    values = []
    for item in data_line.strip().split(','):
        if item == '':
            values.append(0.0)
        else:
            values.append(float(item))
    return values

In [41]:
def create_dict(header, values):
    result = {header:value for header, value in zip(headers, values)}
    return result

In [42]:
def read_csv(file_path):
    result = []
    with open(file_path) as data:
        lines = data.readlines()
        headers = parse_header(line[0])
        for data_line in lines[1:]:
            values = parse_values(data_line)
            item_dict = create_dict(headers, values)
            result.append(item_dict)
    return result